### ISSUE TITLE
SQL Issue

### ISSUE THREAD

**Issue by MateyByrd** [Omniscimus/ExamPoll#1]
When running a local server I get this error

Warning: mysqli::mysqli(): (HY000/2002): No such file or directory in /Users/nickbelzer/Documents/Projects/Webdev/ExamPoll/php/sql/MySQL_Manager.php on line 57

Fatal error: Uncaught exception 'Exception' with message 'Verbinden met de database is mislukt.' in /Users/nickbelzer/Documents/Projects/Webdev/ExamPoll/php/sql/MySQL_Manager.php:59 Stack trace: #0 /Users/nickbelzer/Documents/Projects/Webdev/ExamPoll/php/sql/MySQL_Manager.php(33): MySQL_Manager->connect() #1 /Users/nickbelzer/Documents/Projects/Webdev/ExamPoll/php/sql/ExamPoll_SQL.php(33): MySQL_Manager->getConnection() #2 /Users/nickbelzer/Documents/Projects/Webdev/ExamPoll/php/sql/ExamPoll_SQL.php(19): ExamPoll_SQL->setup_tables() #3 /Users/nickbelzer/Documents/Projects/Webdev/ExamPoll/php/sql/MySQL_Manager.php(19): ExamPoll_SQL->__construct(Object(MySQL_Manager)) #4 /Users/nickbelzer/Documents/Projects/Webdev/ExamPoll/php/Vote_Validator.php(18): MySQL_Manager->__construct() #5 /Users/nickbelzer/Documents/Projects/Webdev/ExamPoll/php/poll.php(4): Vote_Validator->__construct() #6 {main} thrown in /Users/nickbelzer/Documents/Projects/Webdev/ExamPoll/php/sql/MySQL_Manager.php on line 59

**Comment by MateyByrd** [comment]
Problem was solved using 127.0.0.1 instead of localhost as mysql_host
